insert into task (description, color, priority, date_reminder, done) values ('Bact smear-eye', '#903bc3', 3, '2022-09-07', false);
insert into task (description, color, priority, date_reminder, done) values ('Aorta resection & anast', '#9645fc', 3, '2022-09-14', false);
insert into task (description, color, priority, date_reminder, done) values ('Urethral dx proc NEC', '#ecc5e5', 4, '2022-09-13', false);
insert into task (description, color, priority, date_reminder, done) values ('Detach ret photocoag NOS', '#31d915', 1, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('Pressure dressing applic', '#68d89f', 4, '2022-09-12', true);
insert into task (description, color, priority, date_reminder, done) values ('Excision of elbow NEC', '#94b11a', 4, '2022-09-09', false);
insert into task (description, color, priority, date_reminder, done) values ('Remov trunk packing NEC', '#80afaa', 3, '2022-09-07', false);
insert into task (description, color, priority, date_reminder, done) values ('Respiratory measure NEC', '#b5a6c2', 5, '2022-09-13', false);
insert into task (description, color, priority, date_reminder, done) values ('Myelomeningocel repair', '#dee900', 5, '2022-09-08', true);
insert into task (description, color, priority, date_reminder, done) values ('Excis cyst duct remnant', '#e36059', 3, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('Injct/infus glucarpidase', '#a47009', 5, '2022-09-14', true);
insert into task (description, color, priority, date_reminder, done) values ('Conduit artium-pulm art', '#d8c3f8', 1, '2022-09-14', false);
insert into task (description, color, priority, date_reminder, done) values ('Insert valve in vas def', '#54c804', 3, '2022-09-09', true);
insert into task (description, color, priority, date_reminder, done) values ('Closed intra-abd mass bx', '#b132c1', 4, '2022-09-14', true);
insert into task (description, color, priority, date_reminder, done) values ('Uterus/adnex dx proc NEC', '#65fc5f', 5, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Neurectasis', '#f0d56c', 3, '2022-09-10', false);
insert into task (description, color, priority, date_reminder, done) values ('Lap ast vag hysterectomy', '#5a917c', 4, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Adrenal exploration NOS', '#81058e', 1, '2022-09-11', true);
insert into task (description, color, priority, date_reminder, done) values ('Masters'' 2-step test', '#0f46a1', 4, '2022-09-13', false);
insert into task (description, color, priority, date_reminder, done) values ('Skull plate insertion', '#9c873d', 5, '2022-09-14', true);
insert into task (description, color, priority, date_reminder, done) values ('Transfer of finger', '#f50c43', 2, '2022-09-09', false);
insert into task (description, color, priority, date_reminder, done) values ('Angiocardiography NOS', '#f3724f', 2, '2022-09-08', true);
insert into task (description, color, priority, date_reminder, done) values ('Stern esophag anast NEC', '#eccf60', 1, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Visual field study', '#ab36c3', 4, '2022-09-12', false);
insert into task (description, color, priority, date_reminder, done) values ('Aspiration bursa of hand', '#2949a4', 3, '2022-09-10', false);
insert into task (description, color, priority, date_reminder, done) values ('Arthroplasty carpal w/o', '#5f1e71', 5, '2022-09-10', false);
insert into task (description, color, priority, date_reminder, done) values ('C & s-peritoneum', '#79c407', 2, '2022-09-09', false);
insert into task (description, color, priority, date_reminder, done) values ('Inject tranquilizer', '#302837', 4, '2022-09-07', false);
insert into task (description, color, priority, date_reminder, done) values ('Pros rep atrial def-opn', '#059dcd', 5, '2022-09-07', false);
insert into task (description, color, priority, date_reminder, done) values ('Simple mastoidectomy', '#620aba', 2, '2022-09-08', true);
insert into task (description, color, priority, date_reminder, done) values ('Lumbosac spine x-ray NEC', '#fc36ae', 4, '2022-09-11', true);
insert into task (description, color, priority, date_reminder, done) values ('Truncal vagotomy', '#a6d30e', 2, '2022-09-08', false);
insert into task (description, color, priority, date_reminder, done) values ('Peritoneal lavage', '#6062d2', 4, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('Lam keratplast w autgrft', '#266651', 3, '2022-09-14', true);
insert into task (description, color, priority, date_reminder, done) values ('Total ureterectomy', '#dd7bd2', 3, '2022-09-12', true);
insert into task (description, color, priority, date_reminder, done) values ('Bunionect/sft/osteotomy', '#e1cf70', 3, '2022-09-08', false);
insert into task (description, color, priority, date_reminder, done) values ('Posterior rect resection', '#b5d67e', 3, '2022-09-13', false);
insert into task (description, color, priority, date_reminder, done) values ('Endosc inser nasopan tub', '#5ae067', 5, '2022-09-08', false);
insert into task (description, color, priority, date_reminder, done) values ('Cord & epidid repair NEC', '#f48c4d', 1, '2022-09-09', false);
insert into task (description, color, priority, date_reminder, done) values ('Thorac esophagocolos NEC', '#974810', 1, '2022-09-12', true);
insert into task (description, color, priority, date_reminder, done) values ('Intelligence test admin', '#499fa1', 2, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Form cutan ureterostomy', '#2652af', 5, '2022-09-13', false);
insert into task (description, color, priority, date_reminder, done) values ('Inject/infuse NEC', '#42c3c9', 2, '2022-09-14', false);
insert into task (description, color, priority, date_reminder, done) values ('Induct labor-rupt memb', '#3c84fe', 2, '2022-09-12', false);
insert into task (description, color, priority, date_reminder, done) values ('Closed mitral valvotomy', '#f9d246', 1, '2022-09-09', true);
insert into task (description, color, priority, date_reminder, done) values ('Mouth incision NOS', '#012ca6', 2, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Esophageal operation NEC', '#3d28be', 5, '2022-09-07', false);
insert into task (description, color, priority, date_reminder, done) values ('Other gu system exams', '#9eb1fd', 2, '2022-09-12', true);
insert into task (description, color, priority, date_reminder, done) values ('Pneumoencephalogram', '#801b9f', 1, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('Other lacrimal gland ops', '#e29be4', 1, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Limb length proc-humerus', '#439f07', 5, '2022-09-14', false);
insert into task (description, color, priority, date_reminder, done) values ('Destruct peritoneal tiss', '#a98a3e', 1, '2022-09-12', true);
insert into task (description, color, priority, date_reminder, done) values ('Limb length proc-femur', '#9863f7', 5, '2022-09-07', true);
insert into task (description, color, priority, date_reminder, done) values ('Transplant hand musc NEC', '#8c5770', 4, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Remove tracheostomy tube', '#b1087c', 4, '2022-09-09', false);
insert into task (description, color, priority, date_reminder, done) values ('Clos mediastinal biopsy', '#2ac663', 3, '2022-09-09', false);
insert into task (description, color, priority, date_reminder, done) values ('Insert sengstaken tube', '#53ae85', 5, '2022-09-13', false);
insert into task (description, color, priority, date_reminder, done) values ('Micro exam-femal gen NEC', '#0c8ecb', 5, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('Intestinal incision NOS', '#647e7b', 5, '2022-09-14', false);
insert into task (description, color, priority, date_reminder, done) values ('Excis deep cervical node', '#8b1dd0', 3, '2022-09-14', false);
insert into task (description, color, priority, date_reminder, done) values ('Lacrim passage incis NEC', '#00f3b6', 1, '2022-09-13', false);
insert into task (description, color, priority, date_reminder, done) values ('Total parathyroidectomy', '#087f81', 3, '2022-09-07', true);
insert into task (description, color, priority, date_reminder, done) values ('Ther ult head & neck ves', '#a0656f', 2, '2022-09-08', false);
insert into task (description, color, priority, date_reminder, done) values ('Truncal vagotomy', '#82bd0b', 3, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Cerebral thermography', '#38e6b5', 1, '2022-09-09', false);
insert into task (description, color, priority, date_reminder, done) values ('Impl other limb length', '#6f8789', 3, '2022-09-08', false);
insert into task (description, color, priority, date_reminder, done) values ('Salivary cyst marsupial', '#e5f328', 5, '2022-09-07', true);
insert into task (description, color, priority, date_reminder, done) values ('Ovarian denervation', '#518fc2', 1, '2022-09-12', true);
insert into task (description, color, priority, date_reminder, done) values ('Ex cereb meningeal les', '#fdb366', 4, '2022-09-07', true);
insert into task (description, color, priority, date_reminder, done) values ('Removal oth vag pessary', '#8199bc', 5, '2022-09-10', false);
insert into task (description, color, priority, date_reminder, done) values ('Repair oval/round window', '#ac0b6c', 1, '2022-09-11', true);
insert into task (description, color, priority, date_reminder, done) values ('Mri of brain & brainstem', '#2d7ca9', 3, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('Phonocardiogram', '#716ae4', 4, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Fit ext penile prosthes', '#0bea1b', 1, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('Pancreat sphincterotom', '#67cafa', 4, '2022-09-10', true);
insert into task (description, color, priority, date_reminder, done) values ('Size reduct plastic op', '#dbc63a', 4, '2022-09-14', false);
insert into task (description, color, priority, date_reminder, done) values ('Rev jt repl low ext NEC', '#eb489c', 3, '2022-09-10', true);
insert into task (description, color, priority, date_reminder, done) values ('Intravasclr spectroscopy', '#356d4b', 3, '2022-09-09', false);
insert into task (description, color, priority, date_reminder, done) values ('Perc ather extracran vsl', '#bd43a3', 5, '2022-09-13', true);
insert into task (description, color, priority, date_reminder, done) values ('Limb shorten proc NOS', '#ff2472', 1, '2022-09-10', false);
insert into task (description, color, priority, date_reminder, done) values ('Gastric tube irrigat NEC', '#c43713', 3, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('Culture-ent/larynx', '#458dea', 5, '2022-09-08', false);
insert into task (description, color, priority, date_reminder, done) values ('Leg varicos v liga-strip', '#259f65', 3, '2022-09-14', true);
insert into task (description, color, priority, date_reminder, done) values ('Abdominal artery excis', '#eb49bc', 4, '2022-09-10', false);
insert into task (description, color, priority, date_reminder, done) values ('Destruc bartholin gland', '#e7b698', 3, '2022-09-10', false);
insert into task (description, color, priority, date_reminder, done) values ('Labial frenotomy', '#ba0253', 5, '2022-09-09', false);
insert into task (description, color, priority, date_reminder, done) values ('Spine tract w skull dev', '#2f5b34', 3, '2022-09-10', false);
insert into task (description, color, priority, date_reminder, done) values ('Full-thick skin grft NEC', '#2ed512', 5, '2022-09-12', true);
insert into task (description, color, priority, date_reminder, done) values ('App ext fix dev-ring sys', '#bebb47', 1, '2022-09-10', true);
insert into task (description, color, priority, date_reminder, done) values ('Metacarp/carp sequestrec', '#2e86e1', 1, '2022-09-14', true);
insert into task (description, color, priority, date_reminder, done) values ('Exc pituit les-transphen', '#c4b3de', 5, '2022-09-12', true);
insert into task (description, color, priority, date_reminder, done) values ('Ovarian torsion release', '#910101', 5, '2022-09-10', true);
insert into task (description, color, priority, date_reminder, done) values ('Retrobulbar injection', '#cba9e7', 5, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('D & C for preg terminat', '#269043', 2, '2022-09-11', false);
insert into task (description, color, priority, date_reminder, done) values ('Remov mechanical kidney', '#de5f77', 5, '2022-09-14', false);
insert into task (description, color, priority, date_reminder, done) values ('Ins/rep 1 pul gen,rechrg', '#57c3e0', 1, '2022-09-12', false);
insert into task (description, color, priority, date_reminder, done) values ('CAS w CT/CTA', '#329f9c', 5, '2022-09-10', false);
insert into task (description, color, priority, date_reminder, done) values ('Refus lmb/lmbsac pst/pst', '#c140a3', 1, '2022-09-10', true);
insert into task (description, color, priority, date_reminder, done) values ('Excision of hydrocele', '#8f82bd', 2, '2022-09-07', false);
insert into task (description, color, priority, date_reminder, done) values ('Percutaneous angioscopy', '#af454f', 2, '2022-09-07', true);
